export const capLevel1 = [
  { word: "january", isCorrect: false },
  { word: "Canada", isCorrect: true },
  { word: "monday", isCorrect: false },
  { word: "Apple", isCorrect: true },
  { word: "friend", isCorrect: true },
  { word: "paris", isCorrect: false },
  { word: "Dog", isCorrect: true },
  { word: "summer", isCorrect: false },
  { word: "New York", isCorrect: true },
  { word: "school", isCorrect: false },
  { word: "sunflower", isCorrect: false },
  { word: "France", isCorrect: true },
  { word: "friday", isCorrect: false },
  { word: "Python", isCorrect: true },
  { word: "december", isCorrect: false },
  { word: "Japan", isCorrect: true },
  // Sentences start here
  { word: "my favorite subject is english", isCorrect: false },
  { word: "I love Summer vacations.", isCorrect: true },
  { word: "the president lives in Washington.", isCorrect: false },
  { word: "My dog's name is Max.", isCorrect: true },
  { word: "we went to london last year.", isCorrect: false },
  { word: "He gave me a Book.", isCorrect: true }, // assuming this is correct contextually
  { word: "She likes playing Soccer on Sundays.", isCorrect: true },
  { word: "they traveled to india in april.", isCorrect: false },
  { word: "Doctor smith is very kind.", isCorrect: false },
  { word: "The president of the United states is Joe Biden.", isCorrect: true },
  { word: "The capital of France is Berlin.", isCorrect: false },
  { word: "The official language of Canada is English.", isCorrect: false },
  { word: "I am going to the store with my mother.", isCorrect: true },
  { word: "The sun rises in the east.", isCorrect: true },
  {
    word: "The highest mountain in the world is Mount Everest.",
    isCorrect: true,
  },
  { word: "The shortest month of the year is February.", isCorrect: true },
  { word: "Elephant", isCorrect: true },
  { word: "banana", isCorrect: false },
  { word: "Tesla", isCorrect: true },
  { word: "computer", isCorrect: false },
  { word: "River", isCorrect: false },
  { word: "John", isCorrect: true },
  { word: "philippines", isCorrect: false },
  { word: "Manila", isCorrect: true },
  { word: "zebra", isCorrect: false },
  { word: "Microsoft", isCorrect: true },
  { word: "cake", isCorrect: false },
  { word: "Mount Fuji", isCorrect: true },
  { word: "car", isCorrect: false },
  { word: "Africa", isCorrect: true },
  { word: "math", isCorrect: false },
  { word: "Jesus", isCorrect: true },
  { word: "music", isCorrect: false },
  { word: "Amazon", isCorrect: true },
  { word: "I enjoy hiking in the mountains.", isCorrect: true },
  { word: "she visited new zealand last year.", isCorrect: false },
  { word: "My brother lives in Spain.", isCorrect: true },
  { word: "they are reading a Book about World War II.", isCorrect: true },
  { word: "harry potter is my favorite book series.", isCorrect: false },
  { word: "We celebrated Christmas with family.", isCorrect: true },
  { word: "i saw a tiger at the zoo.", isCorrect: false },
  { word: "NASA launched a new satellite.", isCorrect: true },
  { word: "The queen lives in england.", isCorrect: false },
  { word: "Tomorrow is saturday.", isCorrect: false },
  { word: "She visited her Aunt last weekend.", isCorrect: true },
  { word: "paris is beautiful in spring.", isCorrect: false },
  { word: "The library is closed on Mondays.", isCorrect: true },
  { word: "I met professor tanaka yesterday.", isCorrect: false },
  { word: "Have you seen Avatar?", isCorrect: true },
  { word: "They watched a movie called inception.", isCorrect: false },
  { word: "Uncle Joe is coming to dinner.", isCorrect: true },
  { word: "the empire state building is in new york.", isCorrect: false },
  { word: "I want to visit the Eiffel Tower.", isCorrect: true },
  { word: "She works at google.", isCorrect: false },
  { word: "My friend studies Chemistry and Biology.", isCorrect: true },
  { word: "He read the Qur'an in Arabic.", isCorrect: true },
  { word: "we saw the milky way last night.", isCorrect: false },
  { word: "The Pacific Ocean is vast.", isCorrect: true },
  { word: "He traveled from china to korea.", isCorrect: false },
  { word: "The story takes place in Ancient Greece.", isCorrect: true },
  { word: "We visited Grandma in October.", isCorrect: true },
  { word: "i bought a new Phone.", isCorrect: false },
  { word: "She drinks Starbucks every morning.", isCorrect: true },
  { word: "My cousin is learning italian.", isCorrect: false },
  { word: "They stayed at Hilton Hotel.", isCorrect: true },
  { word: "I use facebook to chat with friends.", isCorrect: false },
  { word: "The Bible is a sacred book.", isCorrect: true },
  { word: "He spoke fluent Russian.", isCorrect: true },
  {
    word: "the atlantic ocean is between america and europe.",
    isCorrect: false,
  },
  { word: "I joined the Computer Science club.", isCorrect: true },
  { word: "I want to learn spanish.", isCorrect: false },
  { word: "The Sahara Desert is very hot.", isCorrect: true },
  { word: "we met captain rogers at the museum.", isCorrect: false },
  { word: "She painted a portrait of Vincent van Gogh.", isCorrect: true },
  { word: "I'm attending Harvard University next year.", isCorrect: true },
  { word: "we stayed in tokyo for a week.", isCorrect: false },
  { word: "He gave a speech about World History.", isCorrect: true },
  { word: "She loves reading Poetry.", isCorrect: true },
  { word: "they went hiking in the alps.", isCorrect: false },
  { word: "The Great Wall of China is ancient.", isCorrect: true },
];
