import type { Question } from "../types";

export const capLevel1 = {
  tier1: [
    { word: "Canada", isCorrect: true, correctWord: "Canada" },
    { word: "January", isCorrect: true, correctWord: "January" },
    { word: "February", isCorrect: true, correctWord: "February" },
    { word: "May", isCorrect: true, correctWord: "May" },
    { word: "July", isCorrect: true, correctWord: "July" },
    { word: "September", isCorrect: true, correctWord: "September" },
    { word: "October", isCorrect: true, correctWord: "October" },
    { word: "November", isCorrect: true, correctWord: "November" },
    { word: "Monday", isCorrect: true, correctWord: "Monday" },
    { word: "Tiffany Blue", isCorrect: true, correctWord: "Tiffany Blue" },
    { word: "Wednesday", isCorrect: true, correctWord: "Wednesday" },
    { word: "Thursday", isCorrect: true, correctWord: "Thursday" },
    { word: "Friday", isCorrect: true, correctWord: "Friday" },
    { word: "Saturday", isCorrect: true, correctWord: "Saturday" },
    { word: "Cavite", isCorrect: true, correctWord: "Cavite" },
    { word: "Pampanga", isCorrect: true, correctWord: "Pampanga" },
    { word: "umbrella", isCorrect: false, correctWord: "Umbrella" },
    { word: "dog", isCorrect: false, correctWord: "Dog" },
    { word: "doctor", isCorrect: false, correctWord: "Doctor" },
    { word: "DSWD", isCorrect: true, correctWord: "DSWD" },
    { word: "west", isCorrect: false, correctWord: "West" },
    { word: "Science", isCorrect: true, correctWord: "Science" },
    { word: "landlord", isCorrect: false, correctWord: "Landlord" },
    { word: "tree", isCorrect: false, correctWord: "Tree" },
    { word: "5 p.m.", isCorrect: false, correctWord: "5 p.m." },
    { word: "12nn", isCorrect: false, correctWord: "12nn" },
    { word: "orange", isCorrect: false, correctWord: "Orange" },
    { word: "Titanic", isCorrect: true, correctWord: "Titanic" },
    { word: "Elsa", isCorrect: true, correctWord: "Elsa" },
    { word: "KKK", isCorrect: true, correctWord: "KKK" },
    { word: "book", isCorrect: false, correctWord: "Book" },
    { word: "father", isCorrect: false, correctWord: "Father" },
    { word: "mummy", isCorrect: false, correctWord: "Mummy" },
    { word: "cat", isCorrect: false, correctWord: "Cat" },
    { word: "Catherine", isCorrect: true, correctWord: "Catherine" },
    { word: "Sushi", isCorrect: true, correctWord: "Sushi" },
    { word: "Cheesecake", isCorrect: true, correctWord: "Cheesecake" },
    { word: "Halloween", isCorrect: true, correctWord: "Halloween" },
    { word: "Asia", isCorrect: true, correctWord: "Asia" },
    { word: "France", isCorrect: true, correctWord: "France" },
    { word: "province", isCorrect: false, correctWord: "Province" },
    { word: "city", isCorrect: false, correctWord: "City" },
    { word: "jump", isCorrect: false, correctWord: "Jump" },
    { word: "beautiful", isCorrect: false, correctWord: "Beautiful" },
    { word: "calm", isCorrect: false, correctWord: "Calm" },
    { word: "ring", isCorrect: false, correctWord: "Ring" },
    { word: "earrings", isCorrect: false, correctWord: "Earrings" },
    { word: "pants", isCorrect: false, correctWord: "Pants" },
    { word: "skirt", isCorrect: false, correctWord: "Skirt" },
    { word: "shoes", isCorrect: false, correctWord: "Shoes" },
    { word: "sack", isCorrect: false, correctWord: "Sack" },
    { word: "march", isCorrect: false, correctWord: "March" },
    { word: "April", isCorrect: true, correctWord: "April" },
    { word: "april", isCorrect: false, correctWord: "April" },
    { word: "june", isCorrect: false, correctWord: "June" },
    { word: "June", isCorrect: true, correctWord: "June" },
    { word: "Blue", isCorrect: true, correctWord: "Blue" },
    { word: "blue", isCorrect: false, correctWord: "Blue" },
    { word: "august", isCorrect: false, correctWord: "August" },
    { word: "August", isCorrect: true, correctWord: "August" },
    { word: "december", isCorrect: false, correctWord: "December" },
    { word: "December", isCorrect: true, correctWord: "December" },
    { word: "tuesday", isCorrect: false, correctWord: "Tuesday" },
    { word: "Tuesday", isCorrect: true, correctWord: "Tuesday" },
    { word: "sunday", isCorrect: false, correctWord: "Sunday" },
    { word: "Sunday", isCorrect: true, correctWord: "Sunday" },
    { word: "Baguio", isCorrect: true, correctWord: "Baguio" },
    { word: "baguio", isCorrect: false, correctWord: "Baguio" },
    { word: "philippines", isCorrect: false, correctWord: "Philippines" },
    { word: "Philippines", isCorrect: true, correctWord: "Philippines" },
    { word: "cubao", isCorrect: false, correctWord: "Cubao" },
    { word: "Cubao", isCorrect: true, correctWord: "Cubao" },
    { word: "bulacan", isCorrect: false, correctWord: "Bulacan" },
    { word: "Bulacan", isCorrect: true, correctWord: "Bulacan" },
    { word: "starship", isCorrect: false, correctWord: "Starship" },
    { word: "Starship", isCorrect: true, correctWord: "Starship" },
    { word: "East", isCorrect: true, correctWord: "East" },
    { word: "mathematics", isCorrect: false, correctWord: "Mathematics" },
    { word: "Mathematics", isCorrect: true, correctWord: "Mathematics" },
    { word: "Ruler", isCorrect: true, correctWord: "Ruler" },
    { word: "ruler", isCorrect: false, correctWord: "Ruler" },
    { word: "Banana", isCorrect: true, correctWord: "Banana" },
    { word: "banana", isCorrect: false, correctWord: "Banana" },
    { word: "Grapes", isCorrect: true, correctWord: "Grapes" },
    { word: "grapes", isCorrect: false, correctWord: "Grapes" },
    { word: "olaf", isCorrect: false, correctWord: "Olaf" },
    { word: "Olaf", isCorrect: true, correctWord: "Olaf" },
    { word: "Mother", isCorrect: true, correctWord: "Mother" },
    { word: "mother", isCorrect: false, correctWord: "Mother" },
    { word: "x-men", isCorrect: false, correctWord: "X-men" },
    { word: "X-men", isCorrect: true, correctWord: "X-men" },
    { word: "Pencil", isCorrect: true, correctWord: "Pencil" },
    { word: "pencil", isCorrect: false, correctWord: "Pencil" },
    { word: "loVe", isCorrect: false, correctWord: "Love" },
    { word: "love", isCorrect: false, correctWord: "Love" },
    { word: "PeacE", isCorrect: false, correctWord: "Peace" },
    { word: "peace", isCorrect: false, correctWord: "Peace" },
    { word: "HAIR", isCorrect: false, correctWord: "Hair" },
    { word: "hair", isCorrect: false, correctWord: "Hair" },
    { word: "winD", isCorrect: false, correctWord: "Wind" },
    { word: "wind", isCorrect: false, correctWord: "Wind" },
    { word: "harvarD", isCorrect: false, correctWord: "Harvard" },
    { word: "Harvard", isCorrect: true, correctWord: "Harvard" },
    { word: "rOse", isCorrect: false, correctWord: "Rose" },
    { word: "rose", isCorrect: false, correctWord: "Rose" },
    { word: "Bird", isCorrect: true, correctWord: "Bird" },
    { word: "bird", isCorrect: false, correctWord: "Bird" },
    { word: "porschE", isCorrect: false, correctWord: "Porsche" },
    { word: "Porsche", isCorrect: true, correctWord: "Porsche" },
    { word: "christmas", isCorrect: false, correctWord: "Christmas" },
    { word: "Christmas", isCorrect: true, correctWord: "Christmas" },
    { word: "EuropE", isCorrect: false, correctWord: "Europe" },
    { word: "Europe", isCorrect: true, correctWord: "Europe" },
    { word: "italy", isCorrect: false, correctWord: "Italy" },
    { word: "Italy", isCorrect: true, correctWord: "Italy" },
    { word: "mosQuito", isCorrect: false, correctWord: "Mosquito" },
    { word: "mosquito", isCorrect: false, correctWord: "Mosquito" },
    { word: "shoes", isCorrect: false, correctWord: "Shoes" },
    { word: "Shoes", isCorrect: true, correctWord: "Shoes" },
    { word: "BalenCiaga", isCorrect: false, correctWord: "Balenciaga" },
    { word: "Balenciaga", isCorrect: true, correctWord: "Balenciaga" },
    { word: "david", isCorrect: false, correctWord: "David" },
    { word: "David", isCorrect: true, correctWord: "David" },
    { word: "Coffee", isCorrect: true, correctWord: "Coffee" },
    { word: "coffee", isCorrect: false, correctWord: "Coffee" },
    { word: "Notebook", isCorrect: true, correctWord: "Notebook" },
    { word: "notebook", isCorrect: false, correctWord: "Notebook" },
    { word: "Calendar", isCorrect: true, correctWord: "Calendar" },
    { word: "calendar", isCorrect: false, correctWord: "Calendar" },
    { word: "Desk", isCorrect: true, correctWord: "Desk" },
    { word: "desk", isCorrect: false, correctWord: "Desk" },
    { word: "Teacher", isCorrect: true, correctWord: "Teacher" },
    { word: "teacher", isCorrect: false, correctWord: "Teacher" },
    { word: "Laptop", isCorrect: true, correctWord: "Laptop" },
    { word: "laptop", isCorrect: false, correctWord: "Laptop" },
    { word: "Shoes", isCorrect: true, correctWord: "Shoes" },
    { word: "shoes", isCorrect: false, correctWord: "Shoes" },
    { word: "ched", isCorrect: false, correctWord: "CHED" },
    { word: "CHED", isCorrect: true, correctWord: "CHED" },
    { word: "Senators", isCorrect: true, correctWord: "Senators" },
    { word: "senators", isCorrect: false, correctWord: "Senators" },
    { word: "Mayor", isCorrect: true, correctWord: "Mayor" },
    { word: "mayor", isCorrect: false, correctWord: "Mayor" },
    { word: "Governor", isCorrect: true, correctWord: "Governor" },
    { word: "governor", isCorrect: false, correctWord: "Governor" },
    { word: "Mirror", isCorrect: true, correctWord: "Mirror" },
    { word: "mirror", isCorrect: false, correctWord: "Mirror" },
    { word: "Walk", isCorrect: true, correctWord: "Walk" },
    { word: "walk", isCorrect: false, correctWord: "Walk" },
  ],
  tier2: [
    { word: "new york", isCorrect: false, correctWord: "New York" },
    { word: "John Smith", isCorrect: true, correctWord: "John Smith" },
    { word: "Tiffany Blue", isCorrect: true, correctWord: "Tiffany Blue" },
    { word: "Mt. Mayon", isCorrect: true, correctWord: "Mt. Mayon" },
    { word: "mrs. Santos", isCorrect: false, correctWord: "Mrs. Santos" },
    { word: "Juan dela cruz", isCorrect: false, correctWord: "Juan Dela Cruz" },
    { word: "highway 101", isCorrect: false, correctWord: "Highway 101" },
    {
      word: "south Star Drugstore",
      isCorrect: false,
      correctWord: "South Star Drugstore",
    },
    { word: "North Pacific", isCorrect: true, correctWord: "North Pacific" },
    { word: "West Africa", isCorrect: true, correctWord: "West Africa" },
    { word: "mr. Ybarro", isCorrect: false, correctWord: "Mr. Ybarro" },
    { word: "air force", isCorrect: false, correctWord: "Air Force" },
    {
      word: "bulacan State University",
      isCorrect: false,
      correctWord: "Bulacan State University",
    },
    { word: "eight O'clock", isCorrect: false, correctWord: "Eight O'clock" },
    { word: "Mount Everest", isCorrect: true, correctWord: "Mount Everest" },
    {
      word: "Pride and Prejudice",
      isCorrect: true,
      correctWord: "Pride and Prejudice",
    },
    { word: "Red Cross", isCorrect: true, correctWord: "Red Cross" },
    { word: "World War II", isCorrect: true, correctWord: "World War II" },
    { word: "Father John", isCorrect: true, correctWord: "Father John" },
    { word: "Johny Johny ", isCorrect: false, correctWord: "Johny Johny" },
    {
      word: "The Great Gatsby",
      isCorrect: true,
      correctWord: "The Great Gatsby",
    },
    {
      word: "Doctor Bautista ",
      isCorrect: true,
      correctWord: "Doctor Bautista",
    },
    { word: "Pacific ocean ", isCorrect: false, correctWord: "Pacific Ocean" },
    {
      word: "Great wall Of China",
      isCorrect: false,
      correctWord: "Great Wall of China",
    },
    { word: "star Wars", isCorrect: false, correctWord: "Star Wars" },
    { word: "Labor day", isCorrect: false, correctWord: "Labor Day" },
    {
      word: "Valentine'S Day",
      isCorrect: false,
      correctWord: "Valentine's Day",
    },
    {
      word: "jose Protacio Rizal Mercado y Alonso Realonda",
      isCorrect: false,
      correctWord: "Jose Protacio Rizal Mercado y Alonso Realonda",
    },
    { word: "corazon aquino", isCorrect: false, correctWord: "Corazon Aquino" },
    { word: "manny pacquiao", isCorrect: false, correctWord: "Manny Pacquiao" },
    { word: "hidilyn diaz", isCorrect: false, correctWord: "Hidilyn Diaz" },
    { word: "pia wurtzbach", isCorrect: false, correctWord: "Pia Wurtzbach" },
    { word: "sarah geronimo", isCorrect: false, correctWord: "Sarah Geronimo" },
    { word: "vice ganda", isCorrect: false, correctWord: "Vice Ganda" },
    { word: "angel locsin", isCorrect: false, correctWord: "Angel Locsin" },
    { word: "Nora Aunor", isCorrect: true, correctWord: "Nora Aunor" },
    {
      word: "Fernando Poe Jr.",
      isCorrect: true,
      correctWord: "Fernando Poe Jr.",
    },
    { word: "Kris Aquino", isCorrect: true, correctWord: "Kris Aquino" },
    { word: "Lea Salonga", isCorrect: true, correctWord: "Lea Salonga" },
    {
      word: "Charice Pempengco",
      isCorrect: true,
      correctWord: "Charice Pempengco",
    },
    { word: "Anne Curtis", isCorrect: true, correctWord: "Anne Curtis" },
    {
      word: "Dingdong Dantes",
      isCorrect: true,
      correctWord: "Dingdong Dantes",
    },
    { word: "Marian Rivera", isCorrect: true, correctWord: "Marian Rivera" },
    { word: "Toni Gonzaga", isCorrect: true, correctWord: "Toni Gonzaga" },
    { word: "Robi Domingo", isCorrect: true, correctWord: "Robi Domingo" },
    {
      word: "Sari-Sari Store",
      isCorrect: true,
      correctWord: "Sari-Sari Store",
    },
    { word: "Public Market", isCorrect: true, correctWord: "Public Market" },
    { word: "Barangay Hall", isCorrect: true, correctWord: "Barangay Hall" },
    {
      word: "Tricycle Driver",
      isCorrect: true,
      correctWord: "Tricycle Driver",
    },
    {
      word: "Jeepney Terminal",
      isCorrect: true,
      correctWord: "Jeepney Terminal",
    },
    { word: "Rice Farmer", isCorrect: true, correctWord: "Rice Farmer" },
    { word: "Fish Vendor", isCorrect: true, correctWord: "Fish Vendor" },
    { word: "Street Food", isCorrect: true, correctWord: "Street Food" },
    { word: "Police Officer", isCorrect: true, correctWord: "Police Officer" },
    { word: "Health Center", isCorrect: true, correctWord: "Health Center" },
    {
      word: "Village Captain",
      isCorrect: true,
      correctWord: "Village Captain",
    },
    { word: "Mountain Trail", isCorrect: true, correctWord: "Mountain Trail" },
    { word: "bus station", isCorrect: false, correctWord: "Bus Station" },
    { word: "Flood warning", isCorrect: false, correctWord: "Flood Warning" },
    {
      word: "traffic enforcer",
      isCorrect: false,
      correctWord: "Traffic Enforcer",
    },
    { word: "power outage", isCorrect: false, correctWord: "Power Outage" },
    { word: "barangay tanod", isCorrect: false, correctWord: "Barangay Tanod" },
    { word: "water supply", isCorrect: false, correctWord: "Water Supply" },
    { word: "street sweeper", isCorrect: false, correctWord: "Street Sweeper" },
    { word: "Balikbayan Box", isCorrect: true, correctWord: "Balikbayan Box" },
    { word: "cellphone load", isCorrect: false, correctWord: "Cellphone Load" },
    {
      word: "Barangay Captain",
      isCorrect: true,
      correctWord: "Barangay Captain",
    },
    { word: "face mask", isCorrect: false, correctWord: "Face Mask" },
    { word: "curfew hour", isCorrect: false, correctWord: "Curfew Hour" },
    { word: "storm surge", isCorrect: false, correctWord: "Storm Surge" },
    { word: "relief goods", isCorrect: false, correctWord: "Relief Goods" },
    { word: "election day", isCorrect: false, correctWord: "Election Day" },
    { word: "text message", isCorrect: false, correctWord: "Text Message" },
    { word: "land area", isCorrect: false, correctWord: "Land Area" },
    {
      word: "passport renewal",
      isCorrect: false,
      correctWord: "Passport Renewal",
    },
    { word: "labor strike", isCorrect: false, correctWord: "Labor Strike" },
    { word: "tuition fee", isCorrect: false, correctWord: "Tuition Fee" },
    {
      word: "Housing Project",
      isCorrect: true,
      correctWord: "Housing Project",
    },
    { word: "Job Order", isCorrect: true, correctWord: "Job Order" },
    { word: "Rehab Center", isCorrect: true, correctWord: "Rehab Center" },
    { word: "Fire Drill", isCorrect: true, correctWord: "Fire Drill" },
    { word: "Income Tax", isCorrect: true, correctWord: "Income Tax" },
    { word: "School Paper", isCorrect: true, correctWord: "School Paper" },
    { word: "human rights", isCorrect: false, correctWord: "Human Rights" },
    { word: "social justice", isCorrect: false, correctWord: "Social Justice" },
    { word: "public service", isCorrect: false, correctWord: "Public Service" },
    {
      word: "freedom of speech",
      isCorrect: false,
      correctWord: "Freedom of Speech",
    },
    {
      word: "quality education",
      isCorrect: false,
      correctWord: "Quality Education",
    },
    { word: "national pride", isCorrect: false, correctWord: "National Pride" },
    {
      word: "civic responsibility",
      isCorrect: false,
      correctWord: "Civic Responsibility",
    },
    {
      word: "cultural identity",
      isCorrect: false,
      correctWord: "Cultural Identity",
    },
    {
      word: "economic growth",
      isCorrect: false,
      correctWord: "Economic Growth",
    },
    { word: "political will", isCorrect: false, correctWord: "Political Will" },
    { word: "Moral Values", isCorrect: true, correctWord: "Moral Values" },
    {
      word: "Gender Equality",
      isCorrect: true,
      correctWord: "Gender Equality",
    },
    {
      word: "Disaster Preparedness",
      isCorrect: true,
      correctWord: "Disaster Preparedness",
    },
    {
      word: "Public Awareness",
      isCorrect: true,
      correctWord: "Public Awareness",
    },
    {
      word: "Community Unity",
      isCorrect: true,
      correctWord: "Community Unity",
    },
    { word: "Mental Health", isCorrect: true, correctWord: "Mental Health" },
    {
      word: "Youth Empowerment",
      isCorrect: true,
      correctWord: "Youth Empowerment",
    },
    {
      word: "Environmental Protection",
      isCorrect: true,
      correctWord: "Environmental Protection",
    },
    {
      word: "Equal Opportunity",
      isCorrect: true,
      correctWord: "Equal Opportunity",
    },
  ],
  tier3: [
    {
      word: "Kuya Mark fixed the broken fan.",
      isCorrect: true,
      correctWord: "Kuya Mark fixed the broken fan.",
    },
    {
      word: "Tita Lorna brought pancit for the party.",
      isCorrect: true,
      correctWord: "Tita Lorna brought pancit for the party.",
    },
    {
      word: "Tito Jun arrived from Baguio.",
      isCorrect: true,
      correctWord: "Tito Jun arrived from Baguio.",
    },
    {
      word: "Ana gave chocolates to her classmates.",
      isCorrect: true,
      correctWord: "Ana gave chocolates to her classmates.",
    },
    {
      word: "Elmer rides his bike every morning.",
      isCorrect: true,
      correctWord: "Elmer rides his bike every morning.",
    },
    {
      word: "I live in Quezon City.",
      isCorrect: true,
      correctWord: "I live in Quezon City.",
    },
    {
      word: "We went on a trip to Palawan.",
      isCorrect: true,
      correctWord: "We went on a trip to Palawan.",
    },
    {
      word: "My cousin is from Iloilo.",
      isCorrect: true,
      correctWord: "My cousin is from Iloilo.",
    },
    {
      word: "The mayor of Davao City gave a speech.",
      isCorrect: true,
      correctWord: "The mayor of Davao City gave a speech.",
    },
    {
      word: "We celebrated Independence Day at school.",
      isCorrect: true,
      correctWord: "We celebrated Independence Day at school.",
    },
    {
      word: "Holy Week is a time for reflection.",
      isCorrect: true,
      correctWord: "Holy Week is a time for reflection.",
    },
    {
      word: "The parade during Fiesta is colorful.",
      isCorrect: true,
      correctWord: "The parade during Fiesta is colorful.",
    },
    {
      word: "She wore red on Chinese New Year.",
      isCorrect: true,
      correctWord: "She wore red on Chinese New Year.",
    },
    {
      word: "We prayed during All Saints’ Day.",
      isCorrect: true,
      correctWord: "We prayed during All Saints’ Day.",
    },
    {
      word: "He studies at Ateneo de Manila University.",
      isCorrect: true,
      correctWord: "He studies at Ateneo de Manila University.",
    },
    {
      word: "She is a student of University of the Philippines.",
      isCorrect: true,
      correctWord: "She is a student of University of the Philippines.",
    },
    {
      word: "My brother goes to Philippine Science High School.",
      isCorrect: true,
      correctWord: "My brother goes to Philippine Science High School.",
    },
    {
      word: "We attended a seminar at DepEd.",
      isCorrect: true,
      correctWord: "We attended a seminar at DepEd.",
    },
    {
      word: "My cousin passed the UPCAT.",
      isCorrect: true,
      correctWord: "My cousin passed the UPCAT.",
    },
    {
      word: "My favorite subject is Filipino.",
      isCorrect: true,
      correctWord: "My favorite subject is Filipino.",
    },
    {
      word: "We are learning about Philippine History.",
      isCorrect: true,
      correctWord: "We are learning about Philippine History.",
    },
    {
      word: "She speaks Cebuano fluently.",
      isCorrect: true,
      correctWord: "She speaks Cebuano fluently.",
    },
    {
      word: "I love reading books in English.",
      isCorrect: true,
      correctWord: "I love reading books in English.",
    },
    {
      word: "We had dinner at Jollibee.",
      isCorrect: true,
      correctWord: "We had dinner at Jollibee.",
    },
    {
      word: "I ordered fries from McDonald’s.",
      isCorrect: true,
      correctWord: "I ordered fries from McDonald’s.",
    },
    {
      word: "SM Megamall is always crowded.",
      isCorrect: true,
      correctWord: "SM Megamall is always crowded.",
    },
    {
      word: "I bought shoes at Robinsons Galleria.",
      isCorrect: true,
      correctWord: "I bought shoes at Robinsons Galleria.",
    },
    {
      word: "We stayed at Okada Manila.",
      isCorrect: true,
      correctWord: "We stayed at Okada Manila.",
    },
    {
      word: "The barangay hall is beside the church.",
      isCorrect: true,
      correctWord: "The barangay hall is beside the church.",
    },
    {
      word: "He went to the LTO for his license.",
      isCorrect: true,
      correctWord: "He went to the LTO for his license.",
    },
    {
      word: "My uncle works at DSWD.",
      isCorrect: true,
      correctWord: "My uncle works at DSWD.",
    },
    {
      word: "She filed papers at NBI.",
      isCorrect: true,
      correctWord: "She filed papers at NBI.",
    },
    {
      word: "We visited the DOH website.",
      isCorrect: true,
      correctWord: "We visited the DOH website.",
    },
    {
      word: "She sang Lupang Hinirang during the flag ceremony.",
      isCorrect: true,
      correctWord: "She sang Lupang Hinirang during the flag ceremony.",
    },
    {
      word: "The National Flag was raised proudly.",
      isCorrect: true,
      correctWord: "The National Flag was raised proudly.",
    },
    {
      word: "The Philippine Eagle is endangered.",
      isCorrect: true,
      correctWord: "The Philippine Eagle is endangered.",
    },
    {
      word: "Our national fruit is the mango.",
      isCorrect: true,
      correctWord: "Our national fruit is the mango.",
    },
    {
      word: "They wore Barong Tagalog during the program.",
      isCorrect: true,
      correctWord: "They wore Barong Tagalog during the program.",
    },
    {
      word: "I was born in May.",
      isCorrect: true,
      correctWord: "I was born in May.",
    },
    {
      word: "We go to church every Sunday.",
      isCorrect: true,
      correctWord: "We go to church every Sunday.",
    },
    {
      word: "Classes start again in June.",
      isCorrect: true,
      correctWord: "Classes start again in June.",
    },
    {
      word: "They visited us last Monday.",
      isCorrect: true,
      correctWord: "They visited us last Monday.",
    },
    {
      word: "Mayor Santos visited the school.",
      isCorrect: true,
      correctWord: "Mayor Santos visited the school.",
    },
    {
      word: "President Marcos gave a speech.",
      isCorrect: true,
      correctWord: "President Marcos gave a speech.",
    },
    {
      word: "Dr. Reyes examined the patient.",
      isCorrect: true,
      correctWord: "Dr. Reyes examined the patient.",
    },
    {
      word: "Engr. Cruz designed the building.",
      isCorrect: true,
      correctWord: "Engr. Cruz designed the building.",
    },
    {
      word: "Pastor Joel led the prayer.",
      isCorrect: true,
      correctWord: "Pastor Joel led the prayer.",
    },
    {
      word: "Sir Allan is our Science teacher.",
      isCorrect: true,
      correctWord: "Sir Allan is our Science teacher.",
    },
    {
      word: "maria went to the market.",
      isCorrect: false,
      correctWord: "Maria went to the market.",
    },
    {
      word: "jose bought mangoes from the vendor.",
      isCorrect: false,
      correctWord: "Jose bought mangoes from the vendor.",
    },
    {
      word: "Liza helped her lola cook lunch.",
      isCorrect: false,
      correctWord: "Liza helped her Lola cook lunch.",
    },
    {
      word: "carlo drew a picture of a jeepney.",
      isCorrect: false,
      correctWord: "Carlo drew a picture of a jeepney.",
    },
    {
      word: "Ate Grace teaches Grade 3 students.",
      isCorrect: false,
      correctWord: "Ate Grace teaches Grade 3 students.",
    },
    {
      word: "She grew up in Barangay San roque.",
      isCorrect: false,
      correctWord: "She grew up in Barangay San Roque.",
    },
    {
      word: "We passed through region IV-A on the way.",
      isCorrect: false,
      correctWord: "We passed through Region IV-A on the way.",
    },
    {
      word: "My family is from Nueva ecija.",
      isCorrect: false,
      correctWord: "My family is from Nueva Ecija.",
    },
    {
      word: "La union is known for surfing.",
      isCorrect: false,
      correctWord: "La Union is known for surfing.",
    },
    {
      word: "Iligan city has many waterfalls.",
      isCorrect: false,
      correctWord: "Iligan City has many waterfalls.",
    },
    {
      word: "Bohol is famous for the chocolate hills.",
      isCorrect: false,
      correctWord: "Bohol is famous for the Chocolate Hills.",
    },
    {
      word: "Teachers' day is in October.",
      isCorrect: false,
      correctWord: "Teachers' Day is in October.",
    },
    {
      word: "We watched Fireworks on New Year’s Eve.",
      isCorrect: false,
      correctWord: "We watched fireworks on New Year’s Eve.",
    },
    {
      word: "Bonifacio Day honors a National Hero.",
      isCorrect: false,
      correctWord: "Bonifacio Day honors a national hero.",
    },
    {
      word: "Rizal day is a public holiday.",
      isCorrect: false,
      correctWord: "Rizal Day is a public holiday.",
    },
    {
      word: "My Birthday is in December, near Christmas.",
      isCorrect: false,
      correctWord: "My birthday is in December, near Christmas.",
    },
    {
      word: "They visited Museo pambata.",
      isCorrect: false,
      correctWord: "They visited Museo Pambata.",
    },
    {
      word: "We had a field trip to the National museum.",
      isCorrect: false,
      correctWord: "We had a field trip to the National Museum.",
    },
    {
      word: "she applied at Mapúa University.",
      isCorrect: false,
      correctWord: "She applied at Mapúa University.",
    },
    {
      word: "he graduated from Polytechnic University of the Philippines.",
      isCorrect: false,
      correctWord:
        "He graduated from Polytechnic University of the Philippines.",
    },
    {
      word: "our school is supported by the Department of Education.",
      isCorrect: false,
      correctWord: "Our school is supported by the Department of Education.",
    },
    {
      word: "We discussed ibong adarna in class.",
      isCorrect: false,
      correctWord: "We discussed Ibong Adarna in class.",
    },
    {
      word: "He wrote about noli me tangere.",
      isCorrect: false,
      correctWord: "He wrote about Noli Me Tangere.",
    },
    {
      word: "The story of Alamat ng pinya is interesting.",
      isCorrect: false,
      correctWord: "The story of Alamat ng Pinya is interesting.",
    },
    {
      word: "We watched el Filibusterismo in the library.",
      isCorrect: false,
      correctWord: "We watched El Filibusterismo in the library.",
    },
    {
      word: "Buwan ng Wika is celebrated in august.",
      isCorrect: false,
      correctWord: "Buwan ng Wika is celebrated in August.",
    },
    {
      word: "I am reading a poem by Jose garcia Villa.",
      isCorrect: false,
      correctWord: "I am reading a poem by Jose Garcia Villa.",
    },
    {
      word: "The jeepney stopped near ayala Center.",
      isCorrect: false,
      correctWord: "The jeepney stopped near Ayala Center.",
    },
    {
      word: "She works at bdo",
      isCorrect: false,
      correctWord: "She works at BDO.",
    },
    {
      word: "My parents bank with metrobank.",
      isCorrect: false,
      correctWord: "My parents bank with Metrobank.",
    },
    {
      word: "We had coffee from starbucks.",
      isCorrect: false,
      correctWord: "We had coffee from Starbucks.",
    },
    {
      word: "She bought her dress from bench.",
      isCorrect: false,
      correctWord: "She bought her dress from Bench.",
    },
    {
      word: "He works at the City hall.",
      isCorrect: false,
      correctWord: "He works at the City Hall.",
    },
    {
      word: "they joined the Red Cross training.",
      isCorrect: false,
      correctWord: "They joined the Red Cross training.",
    },
    {
      word: "She volunteers at gawad Kalinga.",
      isCorrect: false,
      correctWord: "She volunteers at Gawad Kalinga.",
    },
    {
      word: "He reported the issue to mmda.",
      isCorrect: false,
      correctWord: "He reported the issue to MMDA.",
    },
    {
      word: "The sangguniang kabataan led the clean-up drive.",
      isCorrect: false,
      correctWord: "The Sangguniang Kabataan led the clean-up drive.",
    },
    {
      word: "The sampaguita is our national flower.",
      isCorrect: false,
      correctWord: "The Sampaguita is our national flower.",
    },
    {
      word: "They discussed the k to 12 program.",
      isCorrect: false,
      correctWord: "They discussed the K to 12 Program.",
    },
    {
      word: "The sona was broadcast on TV.",
      isCorrect: false,
      correctWord: "The SONA was broadcast on TV.",
    },
    {
      word: "The class listened to the national anthem.",
      isCorrect: false,
      correctWord: "The class listened to the National Anthem.",
    },
    {
      word: "They made posters about filipino values month.",
      isCorrect: false,
      correctWord: "They made posters about Filipino Values Month.",
    },
    {
      word: "Our exam is in october.",
      isCorrect: false,
      correctWord: "Our exam is in October.",
    },
    {
      word: "we will travel in april.",
      isCorrect: false,
      correctWord: "We will travel in April.",
    },
    {
      word: "My family celebrates new year every January.",
      isCorrect: false,
      correctWord: "My family celebrates New Year every January.",
    },
    {
      word: "she sent a gift in November.",
      isCorrect: false,
      correctWord: "She sent a gift in November.",
    },
    {
      word: "We cleaned the house on saturday.",
      isCorrect: false,
      correctWord: "We cleaned the house on Saturday.",
    },
    {
      word: "our grades were released on Friday.",
      isCorrect: false,
      correctWord: "Our grades were released on Friday.",
    },
    {
      word: "Miss bianca teaches English.",
      isCorrect: false,
      correctWord: "Miss Bianca teaches English.",
    },
    {
      word: "Judge ramos made the ruling.",
      isCorrect: false,
      correctWord: "Judge Ramos made the ruling.",
    },
    {
      word: "congressman De Leon attended the session.",
      isCorrect: false,
      correctWord: "Congressman De Leon attended the session.",
    },
    {
      word: "Captain mendoza led the rescue team.",
      isCorrect: false,
      correctWord: "Captain Mendoza led the rescue team.",
    },
  ],
};

export const capLevel3 = [
  {
    prompt: "pride and prejudice by jane austen",
    answer: "Pride and Prejudice by Jane Austen",
  },
  {
    prompt: "the lord of the rings by tolkien",
    answer: "The Lord of the Rings by Tolkien",
  },
  {
    prompt: "the statue of liberty is in new york",
    answer: "The Statue of Liberty is in New York",
  },
  {
    prompt: "mt. everest is the highest mountain",
    answer: "Mt. Everest is the highest mountain",
  },
  {
    prompt: "the wizard of oz is a famous movie",
    answer: "The Wizard of Oz is a famous movie",
  },
  {
    prompt: "the usa has 50 states",
    answer: "The USA has 50 states",
  },
  {
    prompt: "the earth orbits the sun",
    answer: "The Earth orbits the Sun",
  },
  {
    prompt: "the highest mountain in japan is mt. fuji",
    answer: "The highest mountain in Japan is Mt. Fuji",
  },
  {
    prompt: "the amazon rainforest is in south america",
    answer: "The Amazon Rainforest is in South America",
  },
  {
    prompt: "the capital of china is beijing",
    answer: "The capital of China is Beijing",
  },
  {
    prompt: "the eiffel tower is in paris",
    answer: "The Eiffel Tower is in Paris",
  },
  {
    prompt: "harry potter was written by jk rowling",
    answer: "Harry Potter was written by J.K. Rowling",
  },
  {
    prompt: "the nile river is the longest river",
    answer: "The Nile River is the longest river",
  },
  {
    prompt: "rome is the capital of italy",
    answer: "Rome is the capital of Italy",
  },
  {
    prompt: "the great wall of china is visible from space",
    answer: "The Great Wall of China is visible from space",
  },
  {
    prompt: "the pacific ocean is the largest ocean",
    answer: "The Pacific Ocean is the largest ocean",
  },
  {
    prompt: "shakespeare wrote hamlet",
    answer: "Shakespeare wrote Hamlet",
  },
  {
    prompt: "the taj mahal is in india",
    answer: "The Taj Mahal is in India",
  },
  {
    prompt: "the leaning tower of pisa is in italy",
    answer: "The Leaning Tower of Pisa is in Italy",
  },
  {
    prompt: "the mona lisa was painted by leonardo da vinci",
    answer: "The Mona Lisa was painted by Leonardo da Vinci",
  },
  {
    prompt: "the pyramids are in egypt",
    answer: "The Pyramids are in Egypt",
  },
  {
    prompt: "the colosseum is in rome",
    answer: "The Colosseum is in Rome",
  },
  {
    prompt: "mars is called the red planet",
    answer: "Mars is called the Red Planet",
  },
  {
    prompt: "the sun is a star",
    answer: "The Sun is a star",
  },
  {
    prompt: "the titanic sank in 1912",
    answer: "The Titanic sank in 1912",
  },
  {
    prompt: "the empire state building is in new york",
    answer: "The Empire State Building is in New York",
  },
  {
    prompt: "william shakespeare was a famous playwright",
    answer: "William Shakespeare was a famous playwright",
  },
  {
    prompt: "the olympics are held every four years",
    answer: "The Olympics are held every four years",
  },
  {
    prompt: "tokyo is the capital of japan",
    answer: "Tokyo is the capital of Japan",
  },
  {
    prompt: "the sahara is the largest desert",
    answer: "The Sahara is the largest desert",
  },
  {
    prompt: "albert einstein developed the theory of relativity",
    answer: "Albert Einstein developed the theory of relativity",
  },
  {
    prompt: "the berlin wall fell in 1989",
    answer: "The Berlin Wall fell in 1989",
  },
  {
    prompt: "the internet was invented in the 20th century",
    answer: "The Internet was invented in the 20th century",
  },
  {
    prompt: "newton discovered gravity",
    answer: "Newton discovered gravity",
  },
  {
    prompt: "the amazon river flows through brazil",
    answer: "The Amazon River flows through Brazil",
  },
  {
    prompt: "the moon orbits the earth",
    answer: "The Moon orbits the Earth",
  },
  {
    prompt: "the leaning tower of pisa leans",
    answer: "The Leaning Tower of Pisa leans",
  },
  {
    prompt: "the golden gate bridge is in san francisco",
    answer: "The Golden Gate Bridge is in San Francisco",
  },
  {
    prompt: "the statue of david was sculpted by michelangelo",
    answer: "The Statue of David was sculpted by Michelangelo",
  },
  {
    prompt: "the currency of japan is yen",
    answer: "The currency of Japan is Yen",
  },
  {
    prompt: "the first man on the moon was neil armstrong",
    answer: "The first man on the Moon was Neil Armstrong",
  },
  {
    prompt: "the leaning tower is in pisa",
    answer: "The Leaning Tower is in Pisa",
  },
  {
    prompt: "the kremlin is in moscow",
    answer: "The Kremlin is in Moscow",
  },
  {
    prompt: "the louvre is a museum in paris",
    answer: "The Louvre is a museum in Paris",
  },
  {
    prompt: "the grand canyon is in arizona",
    answer: "The Grand Canyon is in Arizona",
  },
  {
    prompt: "the sydney opera house is in australia",
    answer: "The Sydney Opera House is in Australia",
  },
  {
    prompt: "the dead sea is below sea level",
    answer: "The Dead Sea is below sea level",
  },
  {
    prompt: "the vatican is the smallest country",
    answer: "The Vatican is the smallest country",
  },
  {
    prompt: "the white house is in washington dc",
    answer: "The White House is in Washington DC",
  },
  {
    prompt: "the parthenon is in athens",
    answer: "The Parthenon is in Athens",
  },
  {
    prompt: "the northern lights can be seen in norway",
    answer: "The Northern Lights can be seen in Norway",
  },
  {
    prompt: "the himalayas are in asia",
    answer: "The Himalayas are in Asia",
  },
  {
    prompt: "napoleon was emperor of france",
    answer: "Napoleon was Emperor of France",
  },
  {
    prompt: "the brooklyn bridge is in new york",
    answer: "The Brooklyn Bridge is in New York",
  },
  {
    prompt: "the leaning tower of pisa was built in the 12th century",
    answer: "The Leaning Tower of Pisa was built in the 12th century",
  },
  {
    prompt: "the louvre holds the mona lisa",
    answer: "The Louvre holds the Mona Lisa",
  },
  {
    prompt: "the antarctic is colder than the arctic",
    answer: "The Antarctic is colder than the Arctic",
  },
  {
    prompt: "the panama canal connects the atlantic and pacific oceans",
    answer: "The Panama Canal connects the Atlantic and Pacific Oceans",
  },
  {
    prompt: "the amazon is the second longest river",
    answer: "The Amazon is the second longest river",
  },
  {
    prompt: "the alps are in europe",
    answer: "The Alps are in Europe",
  },
  {
    prompt: "the berlin wall was torn down in 1989",
    answer: "The Berlin Wall was torn down in 1989",
  },
  {
    prompt: "the titanic hit an iceberg",
    answer: "The Titanic hit an iceberg",
  },
  {
    prompt: "the earth is the third planet from the sun",
    answer: "The Earth is the third planet from the Sun",
  },
  {
    prompt: "pluto is a dwarf planet",
    answer: "Pluto is a dwarf planet",
  },
  {
    prompt: "the olympic games originated in greece",
    answer: "The Olympic Games originated in Greece",
  },
  {
    prompt: "leonardo da vinci painted the last supper",
    answer: "Leonardo da Vinci painted The Last Supper",
  },
  {
    prompt: "the leaning tower took nearly 200 years to build",
    answer: "The Leaning Tower took nearly 200 years to build",
  },
  {
    prompt: "the sydney harbour bridge is in australia",
    answer: "The Sydney Harbour Bridge is in Australia",
  },
  {
    prompt: "the mississippi river flows through the usa",
    answer: "The Mississippi River flows through the USA",
  },
  {
    prompt: "the british museum is in london",
    answer: "The British Museum is in London",
  },
  {
    prompt: "the hollywood sign is in los angeles",
    answer: "The Hollywood Sign is in Los Angeles",
  },
  {
    prompt: "the leaning tower was stabilized in the 1990s",
    answer: "The Leaning Tower was stabilized in the 1990s",
  },
  {
    prompt: "the sagrada familia is in barcelona",
    answer: "The Sagrada Familia is in Barcelona",
  },
  {
    prompt: "the eiffel tower was built in 1889",
    answer: "The Eiffel Tower was built in 1889",
  },
  {
    prompt: "the taj mahal was built by shah jahan",
    answer: "The Taj Mahal was built by Shah Jahan",
  },
  {
    prompt: "the pyramids of giza are in egypt",
    answer: "The Pyramids of Giza are in Egypt",
  },
  {
    prompt: "the united nations headquarters is in new york",
    answer: "The United Nations Headquarters is in New York",
  },
  {
    prompt: "the parthenon was built in ancient greece",
    answer: "The Parthenon was built in Ancient Greece",
  },
  {
    prompt: "the grand bazaar is in istanbul",
    answer: "The Grand Bazaar is in Istanbul",
  },
  {
    prompt: "the london eye is a ferris wheel",
    answer: "The London Eye is a Ferris wheel",
  },
  {
    prompt: "the great barrier reef is off the coast of australia",
    answer: "The Great Barrier Reef is off the coast of Australia",
  },
  {
    prompt: "the christ the redeemer statue is in brazil",
    answer: "The Christ the Redeemer statue is in Brazil",
  },
  {
    prompt: "the rockies are in north america",
    answer: "The Rockies are in North America",
  },
  {
    prompt: "the leaning tower of pisa leans due to soft ground",
    answer: "The Leaning Tower of Pisa leans due to soft ground",
  },
  {
    prompt: "the empire state building has 102 floors",
    answer: "The Empire State Building has 102 floors",
  },
  {
    prompt: "the sphinx is in egypt",
    answer: "The Sphinx is in Egypt",
  },
  {
    prompt: "the tower of london is a historic castle",
    answer: "The Tower of London is a historic castle",
  },
];

export const capLevel2 = {
  tier1: [
    {
      prompt: "the book is on the shelf",
      answer: "The book is on the shelf",
      correctIndexes: [0],
    },
    {
      prompt: "a car stopped near the store",
      answer: "A car stopped near the store",
      correctIndexes: [0],
    },
    {
      prompt: "the child played with a ball",
      answer: "The child played with a ball",
      correctIndexes: [0],
    },
    {
      prompt: "he sat on a wooden chair",
      answer: "He sat on a wooden chair",
      correctIndexes: [0],
    },
    {
      prompt: "i drank a glass of cold water",
      answer: "I drank a glass of cold water",
      correctIndexes: [0],
    },
    {
      prompt: "the cake smells delicious",
      answer: "The cake smells delicious",
      correctIndexes: [0],
    },
    {
      prompt: "a flower bloomed in the garden",
      answer: "A flower bloomed in the garden",
      correctIndexes: [0],
    },
    {
      prompt: "she dropped the pen on the floor",
      answer: "She dropped the pen on the floor",
      correctIndexes: [0],
    },
    {
      prompt: "i heard the sound of a bell",
      answer: "I heard the sound of a bell",
      correctIndexes: [0],
    },
    {
      prompt: "he bought a new laptop last weekend",
      answer: "He bought a new laptop last weekend",
      correctIndexes: [0],
    },
    {
      prompt: "the doctor examined the patient carefully",
      answer: "The doctor examined the patient carefully",
      correctIndexes: [0],
    },
    {
      prompt: "a dog barked loudly in the yard",
      answer: "A dog barked loudly in the yard",
      correctIndexes: [0],
    },
    {
      prompt: "she wore a red dress to the party",
      answer: "She wore a red dress to the party",
      correctIndexes: [0],
    },
    {
      prompt: "i saw a bird flying over the roof",
      answer: "I saw a bird flying over the roof",
      correctIndexes: [0],
    },
    {
      prompt: "the teacher gave homework to the students",
      answer: "The teacher gave homework to the students",
      correctIndexes: [0],
    },
    {
      prompt: "monday is my favorite day of the week",
      answer: "Monday is my favorite day of the week",
      correctIndexes: [0],
    },
    {
      prompt: "google is one of the most popular search engines",
      answer: "Google is one of the most popular search engines",
      correctIndexes: [0],
    },
  ],
  tier2: [
    {
      prompt: "michael jordan played basketball for the chicago bulls",
      answer: "Michael Jordan played basketball for the Chicago Bulls",
      correctIndexes: [0, 2],
    },
    {
      prompt: "new york city is known for its tall skyscrapers",
      answer: "New York City is known for its tall skyscrapers",
      correctIndexes: [0, 1, 2],
    },
    {
      prompt: "the amazon river is the second longest river in the world",
      answer: "The Amazon River is the second longest river in the world",
      correctIndexes: [0, 1, 2],
    },
    {
      prompt: "jennifer lopez performed at the super bowl",
      answer: "Jennifer Lopez performed at the Super Bowl",
      correctIndexes: [0, 1, 6],
    },
    {
      prompt: "eiffel tower is located in paris, france",
      answer: "Eiffel Tower is located in Paris, France",
      correctIndexes: [0, 1, 5, 7],
    },
    {
      prompt: "thanksgiving is celebrated in november",
      answer: "Thanksgiving is celebrated in November",
      correctIndexes: [0, 4],
    },
    {
      prompt: "mount everest is the tallest mountain on earth",
      answer: "Mount Everest is the tallest mountain on Earth",
      correctIndexes: [0, 1, 7],
    },
    {
      prompt: "harvard university is located in massachusetts",
      answer: "Harvard University is located in Massachusetts",
      correctIndexes: [0, 1, 5],
    },
  ],
  tier3: [
    {
      prompt: "i met john and sarah at the morgan library",
      answer: "I met John and Sarah at the Morgan Library",
      correctIndexes: [0, 2, 4, 7, 8],
    },
    {
      prompt: "google and microsoft are tech giants",
      answer: "Google and Microsoft are tech giants",
      correctIndexes: [0, 2],
    },
    {
      prompt: "we traveled to paris during spring break",
      answer: "We traveled to Paris during Spring Break",
      correctIndexes: [0, 3, 5],
    },
    {
      prompt: "uncle ben always made the best pancakes",
      answer: "Uncle Ben always made the best Pancakes",
      correctIndexes: [0, 2, 7],
    },
    {
      prompt: "apple announced the new iphone in california",
      answer: "Apple announced the new iPhone in California",
      correctIndexes: [0, 5, 7],
    },
    {
      prompt: "luna saw a shooting star over mount fuji",
      answer: "Luna saw a shooting star over Mount Fuji",
      correctIndexes: [0, 7, 8],
    },
    {
      prompt: "the great wall is in china",
      answer: "The Great Wall is in China",
      correctIndexes: [0, 1, 4],
    },
    {
      prompt: "i watched titanic with emily last night",
      answer: "I watched Titanic with Emily last night",
      correctIndexes: [0, 2, 4],
    },
    {
      prompt: "santa claus comes every christmas eve",
      answer: "Santa Claus comes every Christmas Eve",
      correctIndexes: [0, 1, 4, 5],
    },
    {
      prompt: "harvard and yale are ivy league schools",
      answer: "Harvard and Yale are Ivy League schools",
      correctIndexes: [0, 2, 4, 5],
    },
    {
      prompt: "mr. smith teaches history on mondays",
      answer: "Mr. Smith teaches History on Mondays",
      correctIndexes: [0, 1, 3, 5],
    },
    {
      prompt: "the amazon river is the longest in south america",
      answer: "The Amazon River is the longest in South America",
      correctIndexes: [0, 1, 2, 7, 8],
    },
  ],
};

export const practiceQuestions: Question[] = [
  {
    question: "Which sentence is correctly written?",
    choices: [
      "how are you doing today",
      "How are you doing today?",
      "How are you doing today.",
      "how are you doing today!",
    ],
    answerIndex: 1,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "I love chocolate cake. Do you?",
      "I love chocolate cake do you.",
      "i love chocolate cake. do you?",
      "I love chocolate cake do you",
    ],
    answerIndex: 0,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "It was a beautifull day yesterday",
      "It was a beautiful day yesterday.",
      "it was a beautiful day yesterday.",
      "It was a beautiful day Yesterday",
    ],
    answerIndex: 1,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "Shes going to the park to play with her freinds.",
      "She is going to the park to play with her friends",
      "She’s going to the park to play with her friends.",
      "shes going to the park to play with her friends",
    ],
    answerIndex: 2,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "wow that was amazing",
      "Wow. That was amazing.",
      "wow, that was amazing.",
      "Wow! That was amazing.",
    ],
    answerIndex: 3,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "We should visit the library and buy some books.",
      "we should visit the library and buy some books",
      "We should visit the libray and buy some books.",
      "We should visit the library and buy some Books",
    ],
    answerIndex: 0,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "Lets go for a walk tomorrow morning",
      "Let’s go for a walk tomorrow morning.",
      "Let’s go for a walk tomorrow Morning",
      "let’s go for a walk tomorrow morning",
    ],
    answerIndex: 1,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "The concert is next Saturday do you want to go",
      "the concert is next Saturday. Do you want to go",
      "The concert is next Saturday. Do you want to go?",
      "The concert is next Saturday do you want to go?",
    ],
    answerIndex: 2,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "My brothers name is michael.",
      "My brother’s name is Michael.",
      "my brother’s name is Michael.",
      "My brother’s name is michael",
    ],
    answerIndex: 1,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "Please hand me the pen, its on the table.",
      "Please hand me the pen. It’s on the table.",
      "Please hand me the pen; it’s on the table.",
      "Please hand me the pen it’s on the table.",
    ],
    answerIndex: 2,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "i want to buy a new backpack from the store.",
      "I want to buy a new backpack from the store.",
      "I want to buy a new backpack from the Store.",
      "I want to buy new backpack from the store",
    ],
    answerIndex: 1,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "the professor gave an interesting lecture on physics.",
      "The Professor gave an interesting lecture on Physics.",
      "The professor gave an interesting lecture on physics.",
      "The professor gave an interesting Lecture on physics",
    ],
    answerIndex: 2,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "She said i will come after lunch.",
      "She said I will come after lunch.",
      "She said, “I will come after lunch.”",
      "She said “I will come after lunch”",
    ],
    answerIndex: 2,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "We went to the beach, it was hot and sunny.",
      "We went to the beach. It was hot and sunny.",
      "We went to the beach; it was hot and sunny.",
      "We went to the beach it was hot and sunny",
    ],
    answerIndex: 2,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "He loves reading books about history and scifi.",
      "He loves reading books about history and sci-fi.",
      "he loves reading books about history and sci fi.",
      "He loves reading books about History and Sci-fi",
    ],
    answerIndex: 1,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "The team played hard but lost the game.",
      "The team played hard, but lost the game.",
      "the team played hard but lost the game.",
      "The team played hard, but lost the Game",
    ],
    answerIndex: 0,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "I visited the musuem last weekend.",
      "i visited the museum last weekend.",
      "I visited the museum last weekend.",
      "I visited the Museum last weekend",
    ],
    answerIndex: 2,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "He wanted a pizza for lunch, but we had pasta.",
      "He wanted a pizza for lunch but we had pasta.",
      "He wanted a pizza, for lunch but we had pasta.",
      "he wanted a pizza for lunch, but we had pasta",
    ],
    answerIndex: 0,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "She gave me a pretty bracelet as a gift.",
      "She gave me a pretty Bracelet as a gift.",
      "she gave me a pretty bracelet as a gift.",
      "She gave me a pretty bracelet as a Gift",
    ],
    answerIndex: 0,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "Please dont forget your homework tomorrow.",
      "Please don't forget your homework tomorrow.",
      "please don’t forget your homework tomorrow.",
      "Please don’t forget your homework tomorrow.",
    ],
    answerIndex: 3,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "The movie was fantastic, we should watch it again.",
      "The movie was fantastic. We should watch it again.",
      "The movie was fantastic! We should watch it again.",
      "the movie was fantastic! We should watch it again.",
    ],
    answerIndex: 2,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "I need to buy some shoes and a coat.",
      "i need to buy some shoes and a coat.",
      "I need to buy some shoes, and a coat.",
      "I need to buy some shoes and a Coat.",
    ],
    answerIndex: 0,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "Have you seen my book its missing.",
      "Have you seen my book? It’s missing.",
      "have you seen my book? It’s missing.",
      "Have you seen my book, it’s missing?",
    ],
    answerIndex: 1,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "My favrite color is blue.",
      "My favorite color is blue.",
      "my favorite color is blue.",
      "My favorite Color is blue.",
    ],
    answerIndex: 1,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "My parents are going to paris for the holidays.",
      "my parents are going to Paris for the holidays.",
      "My parents are going to Paris for the holidays.",
      "My parents are going to paris for the Holidays.",
    ],
    answerIndex: 2,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "She loves to read novels about adventures.",
      "she loves to read novels about adventures.",
      "She loves to read novels about Adventures.",
      "She loves to read Novels about adventures.",
    ],
    answerIndex: 0,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "You should take an umbrella, it’s raining outside.",
      "You should take an umbrella it’s raining outside.",
      "You should take an umbrella. It’s raining outside.",
      "You should take an umbrella; it’s raining outside.",
    ],
    answerIndex: 3,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "I got a letter from my friend last week.",
      "i got a letter from my friend last week.",
      "I got a Letter from my friend last week.",
      "I got a letter from my friend Last week.",
    ],
    answerIndex: 0,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "She plays the violin beautifully.",
      "She plays the Violin beautifully.",
      "she plays the violin beautifully.",
      "She play the violin beautifully.",
    ],
    answerIndex: 0,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "The class starts at 9 am tomorrow.",
      "the class starts at 9 AM tomorrow.",
      "The class starts at 9 a.m. tomorrow.",
      "The Class starts at 9 a.m. tomorrow.",
    ],
    answerIndex: 2,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "I enjoy watching sports on TV.",
      "i enjoy watching sports on TV.",
      "I enjoy watching sports on tv.",
      "I enjoy watching Sports on TV.",
    ],
    answerIndex: 0,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "We will have a big Party for his birthday.",
      "We will have a big party for his birthday.",
      "We will have a Big party for his Birthday.",
      "we will have a big party for his birthday.",
    ],
    answerIndex: 1,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "There is a new restaurant near my house.",
      "There is a new resturant near my house.",
      "there is a new restaurant near my house.",
      "There is a new restaurant Near my house.",
    ],
    answerIndex: 0,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "They went on a vacation to new york city.",
      "They went on a vacation to New York City.",
      "they went on a vacation to New York City.",
      "They went on a Vacation to New York City.",
    ],
    answerIndex: 1,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "I cant believe how quickly the time has passed.",
      "I can't believe how quickly the time has passed.",
      "I can’t believe how quickly the time has passed.",
      "i can’t believe how quickly the time has passed.",
    ],
    answerIndex: 2,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "The train leaves at 5 oclock.",
      "The train leaves at 5 o’clock.",
      "the train leaves at 5 o’clock.",
      "The Train leaves at 5 o’clock.",
    ],
    answerIndex: 1,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "He asked if we were ready for the race.",
      "he asked if we were ready for the race.",
      "He asked if we were ready for the Race.",
      "He asked if we were Ready for the race.",
    ],
    answerIndex: 0,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "His favorite subject is Maths.",
      "His favorite subject is Math.",
      "His favorite Subject is math.",
      "His Favorite subject is math.",
    ],
    answerIndex: 1,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "We should study for the Test.",
      "We should Study for the test.",
      "we should study for the test.",
      "We should study for the test.",
    ],
    answerIndex: 3,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "The house was decorated with beautiful flowers.",
      "The house was decorated with beautiful Flowrs.",
      "The House was decorated with beautiful flowers.",
      "the house was decorated with beautiful flowers.",
    ],
    answerIndex: 0,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "The store is closed on Sunday.",
      "The store is closed on sunday.",
      "The store is closed on Sunday.",
      "The store is closed on Sunday.",
    ],
    answerIndex: 0,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "I want to eat pizza and pasta for dinner.",
      "I want to eat pizza and pasta for dinner.",
      "I want to eat pizza and pasta for dinner.",
      "I want to eat pizza and pasta for dinner.",
    ],
    answerIndex: 0,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "Please take care of the dog while I’m away.",
      "Please take care of the dog while I’m away.",
      "Please take care of the dog while I'm away.",
      "Please take care of the dog while I'm away.",
    ],
    answerIndex: 0,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "Can you help me with this exercise?",
      "Can you help me with this excersize?",
      "Can you help me with this excersize?",
      "Can you help me with this exercise?",
    ],
    answerIndex: 0,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "We met at the café for a coffee.",
      "We met at the café for a coffee.",
      "We met at the cafe for a coffee.",
      "We met at the café for a coffee.",
    ],
    answerIndex: 0,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "Her hair is long and brown.",
      "Her hair is long and brown.",
      "Her hair is long and brown.",
      "Her hair is long and brown.",
    ],
    answerIndex: 0,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "Don’t forget to lock the door.",
      "Dont forget to lock the door.",
      "Don’t forget to lock the door.",
      "Don't forget to lock the door.",
    ],
    answerIndex: 0,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "The cat jumped off the sofa.",
      "The cat jumped off the sofa.",
      "The cat jumped off the sofa.",
      "The cat jumped off the sofa.",
    ],
    answerIndex: 0,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "He studies at Harvard University.",
      "He studies at Harvard University.",
      "He studies at Harvard University.",
      "He studies at harvard university.",
    ],
    answerIndex: 0,
  },
  {
    question: "Which sentence is correctly written?",
    choices: [
      "I love the beach, its so relaxing.",
      "I love the beach, it’s so relaxing.",
      "I love the beach; it’s so relaxing.",
      "I love the beach, it’s so relaxing.",
    ],
    answerIndex: 2,
  },
];
